/**
 * SmartSuggestionsCard.tsx
 *
 * Displays AI-generated emergency response suggestions derived from
 * extracted entities. 100% local/free — generated by spaCy + rule engine.
 *
 * Sections:
 *   1. Response Level banner (standard / elevated / critical)
 *   2. Priority Actions  — ordered immediate steps
 *   3. Resources to Dispatch
 *   4. Dispatcher Notes
 *   5. Follow-up Checklist
 */

import { useState } from 'react';
import { useTranslation } from '../../context/TranslationContext';
import {
    Zap, Shield, AlertTriangle, AlertOctagon,
    CheckCircle, ChevronDown, ChevronUp,
    Radio, ClipboardList, Phone, ListChecks,
    Truck,
} from 'lucide-react';
import type { SmartSuggestions } from '../../services/api';

type Props = {
    suggestions: SmartSuggestions;
};

// ── Response level config ──────────────────────────────────────
const LEVEL_CFG = {
    standard: {
        bg: '#f0fdf4', border: '#86efac', color: '#166534',
        icon: <Shield size={22} />, label: 'STANDARD RESPONSE',
        desc: 'Routine response — follow standard procedures',
        pulse: false,
    },
    elevated: {
        bg: '#fffbeb', border: '#fcd34d', color: '#92400e',
        icon: <AlertTriangle size={22} />, label: 'ELEVATED RESPONSE',
        desc: 'Heightened alert — expedite dispatch and monitor closely',
        pulse: false,
    },
    critical: {
        bg: '#fff1f2', border: '#f87171', color: '#991b1b',
        icon: <AlertOctagon size={22} />, label: 'CRITICAL RESPONSE',
        desc: 'All available units — immediate action required',
        pulse: true,
    },
};

// ── Collapsible section wrapper ────────────────────────────────
function Section({
    icon, title, color, bg, border, children, defaultOpen = true,
}: {
    icon: React.ReactNode;
    title: string;
    color: string;
    bg: string;
    border: string;
    children: React.ReactNode;
    defaultOpen?: boolean;
}) {
    const [open, setOpen] = useState(defaultOpen);
    return (
        <div style={{ border: `1.5px solid ${border}`, borderRadius: 12, overflow: 'hidden' }}>
            <button
                onClick={() => setOpen(o => !o)}
                style={{
                    width: '100%', display: 'flex', alignItems: 'center',
                    justifyContent: 'space-between',
                    padding: '13px 18px', background: bg,
                    border: 'none', cursor: 'pointer',
                }}
            >
                <div style={{ display: 'flex', alignItems: 'center', gap: 10, color }}>
                    {icon}
                    <span style={{ fontWeight: 700, fontSize: 14, letterSpacing: '0.3px' }}>
                        {title}
                    </span>
                </div>
                {open
                    ? <ChevronUp size={16} color={color} />
                    : <ChevronDown size={16} color={color} />}
            </button>
            {open && (
                <div style={{ background: 'white', padding: '14px 18px' }}>
                    {children}
                </div>
            )}
        </div>
    );
}

// ── Action item row ────────────────────────────────────────────
function ActionItem({ text, index }: { text: string; index: number }) {
    const isWarning = text.startsWith('⚠️') || text.startsWith('CRITICAL') || text.startsWith('HIGH');
    const isCovert  = text.startsWith('⚠️  COVERT');

    return (
        <div style={{
            display: 'flex', gap: 12, alignItems: 'flex-start',
            padding: '9px 12px',
            background: isCovert ? '#fff1f2' : isWarning ? '#fffbeb' : index % 2 === 0 ? '#f8fafc' : 'white',
            borderRadius: 8,
            border: isCovert ? '1px solid #fecaca' : isWarning ? '1px solid #fde68a' : '1px solid transparent',
            marginBottom: 6,
        }}>
            <div style={{
                width: 24, height: 24, borderRadius: '50%', flexShrink: 0,
                background: isCovert ? '#dc2626' : isWarning ? '#f59e0b' : '#1a3a6b',
                color: 'white', display: 'flex', alignItems: 'center',
                justifyContent: 'center', fontSize: 12, fontWeight: 700, marginTop: 1,
            }}>
                {index + 1}
            </div>
            <span style={{
                fontSize: 13.5, color: isCovert ? '#991b1b' : isWarning ? '#92400e' : '#1e293b',
                lineHeight: 1.55, fontWeight: isWarning ? 600 : 400,
            }}>
                {text}
            </span>
        </div>
    );
}

// ── Resource badge ─────────────────────────────────────────────
function ResourceBadge({ text }: { text: string }) {
    const isMedical  = /samu|ambulance|medical|sécour|إسعاف/i.test(text);
    const isPolice   = /police|gendarmerie|شرطة/i.test(text);
    const isFire     = /pompier|fire|إطفاء/i.test(text);
    const isMass     = /mass|civil|cump/i.test(text);

    const color = isMass ? '#7c3aed' : isMedical ? '#059669' : isPolice ? '#1d4ed8' : isFire ? '#dc2626' : '#374151';
    const bg    = isMass ? '#f5f3ff' : isMedical ? '#f0fdf4' : isPolice ? '#eff6ff' : isFire ? '#fff1f2' : '#f8fafc';
    const border= isMass ? '#c4b5fd' : isMedical ? '#a7f3d0' : isPolice ? '#bfdbfe' : isFire ? '#fecaca' : '#e2e8f0';

    return (
        <div style={{
            display: 'inline-flex', alignItems: 'center', gap: 7,
            background: bg, color, border: `1.5px solid ${border}`,
            borderRadius: 8, padding: '7px 14px',
            fontSize: 13, fontWeight: 600,
        }}>
            <Truck size={14} />
            {text}
        </div>
    );
}

// ── Checklist item ─────────────────────────────────────────────
function CheckItem({ text, warn }: { text: string; warn?: boolean }) {
    const [checked, setChecked] = useState(false);
    return (
        <div
            onClick={() => setChecked(c => !c)}
            style={{
                display: 'flex', gap: 10, alignItems: 'flex-start',
                padding: '8px 10px', borderRadius: 7, cursor: 'pointer',
                background: checked ? '#f0fdf4' : warn ? '#fffbeb' : 'transparent',
                border: `1px solid ${checked ? '#bbf7d0' : warn ? '#fde68a' : '#f1f5f9'}`,
                marginBottom: 5, transition: 'all 0.15s',
            }}
        >
            <div style={{
                width: 20, height: 20, borderRadius: 5, flexShrink: 0,
                border: `2px solid ${checked ? '#16a34a' : warn ? '#f59e0b' : '#94a3b8'}`,
                background: checked ? '#16a34a' : 'white',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                marginTop: 1, transition: 'all 0.15s',
            }}>
                {checked && <CheckCircle size={13} color="white" />}
            </div>
            <span style={{
                fontSize: 13.5, lineHeight: 1.5,
                color: checked ? '#166534' : warn ? '#92400e' : '#334155',
                textDecoration: checked ? 'line-through' : 'none',
                fontWeight: warn ? 600 : 400,
            }}>
                {text}
            </span>
        </div>
    );
}

// ── Main component ─────────────────────────────────────────────
export default function SmartSuggestionsCard({ suggestions }: Props) {
    const { t } = useTranslation();
    const level = suggestions.estimated_response_level || 'standard';
    const cfg   = LEVEL_CFG[level] || LEVEL_CFG.standard;

    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            <style>{`
                @keyframes pulseRed {
                    0%, 100% { box-shadow: 0 0 0 0 rgba(220,38,38,0.4); }
                    50%       { box-shadow: 0 0 0 8px rgba(220,38,38,0); }
                }
            `}</style>

            {/* ── Header ── */}
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 2 }}>
                <div style={{
                    width: 32, height: 32, borderRadius: 8,
                    background: '#fef3c7',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                }}>
                    <Zap size={18} color="#d97706" />
                </div>
                <div>
                    <div style={{ fontWeight: 800, color: '#1a3a6b', fontSize: 15 }}>
                        {t('smartSuggestionsLabel') || 'Smart Emergency Suggestions'}
                    </div>
                    <div style={{ fontSize: 12, color: '#94a3b8' }}>
                        Generated locally — no API · 100% free
                    </div>
                </div>
            </div>

            {/* ── Response Level Banner ── */}
            <div style={{
                display: 'flex', alignItems: 'center', gap: 16,
                padding: '14px 20px',
                background: cfg.bg,
                border: `2px solid ${cfg.border}`,
                borderRadius: 12,
                animation: cfg.pulse ? 'pulseRed 2s ease-in-out infinite' : undefined,
            }}>
                <div style={{
                    width: 48, height: 48, borderRadius: 12,
                    background: `${cfg.color}18`,
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    color: cfg.color, flexShrink: 0,
                }}>
                    {cfg.icon}
                </div>
                <div>
                    <div style={{ fontWeight: 800, fontSize: 16, color: cfg.color }}>
                        {t('responseLevel') || 'RESPONSE LEVEL'}: {cfg.label}
                    </div>
                    <div style={{ fontSize: 13, color: '#64748b', marginTop: 2 }}>
                        {cfg.desc}
                    </div>
                </div>
            </div>

            {/* ── Priority Actions ── */}
            {suggestions.priority_actions?.length > 0 && (
                <Section
                    icon={<AlertTriangle size={16} />}
                    title={`${t('priorityActionsLabel') || 'Priority Actions'} (${suggestions.priority_actions.length})`}
                    color="#92400e"
                    bg="#fffbeb"
                    border="#fde68a"
                    defaultOpen={true}
                >
                    {suggestions.priority_actions.map((action, i) => (
                        <ActionItem key={i} text={action} index={i} />
                    ))}
                </Section>
            )}

            {/* ── Resources ── */}
            {suggestions.resources_to_dispatch?.length > 0 && (
                <Section
                    icon={<Radio size={16} />}
                    title={t('resourcesToDispatchLabel') || 'Resources to Dispatch'}
                    color="#1d4ed8"
                    bg="#eff6ff"
                    border="#bfdbfe"
                    defaultOpen={true}
                >
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, paddingTop: 4 }}>
                        {suggestions.resources_to_dispatch.map((r, i) => (
                            <ResourceBadge key={i} text={r} />
                        ))}
                    </div>
                </Section>
            )}

            {/* ── Dispatcher Notes ── */}
            {suggestions.dispatcher_notes?.length > 0 && (
                <Section
                    icon={<ClipboardList size={16} />}
                    title={t('dispatcherNotesLabel') || 'Dispatcher Notes'}
                    color="#374151"
                    bg="#f8fafc"
                    border="#e2e8f0"
                    defaultOpen={true}
                >
                    {suggestions.dispatcher_notes.map((note, i) => {
                        const isWarn = note.startsWith('⚠️') || note.startsWith('Anomaly');
                        return (
                            <div key={i} style={{
                                display: 'flex', gap: 8, alignItems: 'flex-start',
                                padding: '7px 10px', borderRadius: 7, marginBottom: 4,
                                background: isWarn ? '#fffbeb' : i % 2 === 0 ? '#f8fafc' : 'white',
                                border: `1px solid ${isWarn ? '#fde68a' : '#f1f5f9'}`,
                            }}>
                                <Phone size={13} color={isWarn ? '#f59e0b' : '#94a3b8'} style={{ flexShrink: 0, marginTop: 2 }} />
                                <span style={{
                                    fontSize: 13, color: isWarn ? '#92400e' : '#475569',
                                    fontWeight: isWarn ? 600 : 400, lineHeight: 1.5,
                                }}>
                                    {note}
                                </span>
                            </div>
                        );
                    })}
                </Section>
            )}

            {/* ── Follow-up Checklist ── */}
            {suggestions.follow_up_checklist?.length > 0 && (
                <Section
                    icon={<ListChecks size={16} />}
                    title={t('followUpChecklistLabel') || 'Follow-up Checklist'}
                    color="#166534"
                    bg="#f0fdf4"
                    border="#bbf7d0"
                    defaultOpen={false}
                >
                    <p style={{ fontSize: 12, color: '#94a3b8', marginBottom: 10 }}>
                        Click items to mark as completed
                    </p>
                    {suggestions.follow_up_checklist.map((item, i) => (
                        <CheckItem
                            key={i}
                            text={item}
                            warn={item.toLowerCase().includes('flag') || item.toLowerCase().includes('supervisor')}
                        />
                    ))}
                </Section>
            )}
        </div>
    );
}